### ISSUE TITLE
Proposal idea: Incorporate capability to call turnip features from within rspec

### ISSUE THREAD

**Issue by lukaso** [jnicklas/turnip#159]
We've developed a gem https://github.com/simplybusiness/rutabaga which allows turnip features to be called from within an rspec `declare` block. 

This allows users to avoid the complexities of having lots of `@` flags on their features, and makes it easy to use features to test controllers in rails (for example). This functionality is similar to how I believe CucumberJVM works.

The reason for suggesting incorporating it, is that it has had to be built essentially as a monkeypatch on top of turnip, whereas I believe incorporating it in, would clean the code up. But equally, it needs to be useful as a core capability.

I suppose the other approach would be to add hooks to jnicklas/turnip to make the feature less of a monkeypatch.

**Comment by gongo** [comment]
Hi @lukaso . Thanks for proposal.
But, I think turnip is not necessary to incorporate its feature.

Turnip's work is to provide a mechanism "linking from the scenario to the test case" **only**.
If add a reverse mechanism, how to use turnip becomes complex.
And, turnip's source code becomes complex instead of rutabaga.

(Therefore, it is very good that another gem (rutabaga) has a reverse mechanism.)
