### ISSUE TITLE
Given-When-Then defined as given/when/then

### ISSUE THREAD

**Issue by sellittf** [jnicklas/turnip#176]
I remember years ago I was writing scenarios in cucumber which then each "conjuction" was matched separately, making not reusable the same step like "Given I am logged in", "When I am logged in", "Then I am logged in".
Is it possible to have in turnip something similar?
So that Given => given, When => when, Then => then.

I know that having just "step" it's much more convenient and easier for the matching also the And, etc...

Well, my purpose is:

```
given 'I am logged id' do
  # implementation
end

when 'I am logged id' do
  # other implementation
end

then 'I am logged id' do
  # yet another implementation
end
```

Thanks

**Comment by jnicklas** [comment]
The last time I looked into this, the Gherkin parser which turnip uses did not provide which keyword the step started with in any sensible way. The problem is that Gherkin is internationalized, and the list of keywords can vary, but the parser does not provide any canonical version, only how the keyword appeared in the feature file. It also would require us to manually keep track of `And` and `But`, since the parser doesn't normalize those either (and again, they could be in a different language).

Unless they've changed how this works in the Gherkin parser then there isn't really any non-horrible way of implementing this.

**Comment by sellittf** [comment]
Yep, it's clear. Thanks
